export interface AppUser {
  uid: string;
  email: string | null;
  role: 'admin' | 'owner' | 'member';
  companyId?: string;
  trialEndsAt?: number; // Unix timestamp in milliseconds
}

export interface Tax {
  name: string;
  rate: number;
}

export interface Company {
  id: string;
  name: string;
  ownerId: string;
  industry: string;
  programs: string[];
  subscriptionPlan: 'basic' | 'professional' | 'enterprise' | 'trial';
  address?: string;
  phone?: string;
  email?: string;
  website?: string;
  taxNumber?: string;
  taxCardNumber?: string;
  currency?: string;
  timezone?: string;
  taxes?: Tax[];
}

export interface Program {
  id: string;
  name: string;
  description: string;
}

export interface CompanyMember {
    uid: string;
    email: string | null;
    role: 'owner' | 'member';
}

export interface PageContent {
  id: string;
  title: string;
  content: string;
}

export interface PricingPlan {
    id: string;
    name: string;
    description: string;
    price: number | string;
    currency: string;
    pricePeriod: string;
    features: string[];
    ctaText: string;
    ctaLink: string;
    highlighted?: boolean;
    disclaimer?: string;
}

export interface Employee {
  id: string;
  name: string;
  position: string;
  hireDate: string;
  salary: number;
  status: 'active' | 'inactive';
  departmentId?: string;
  departmentName?: string;
}

export interface Department {
  id: string;
  name: string;
}

export interface JobOpening {
  id: string;
  title: string;
  department: string;
  description: string;
  status: 'open' | 'closed';
  requiredEmployees: number;
  requestDate: string;
  hiredCount: number;
}

export interface Candidate {
  id: string;
  name: string;
  email: string;
  phone: string;
  status: 'applied' | 'screening' | 'interview' | 'hired' | 'rejected';
  address?: string;
  maritalStatus?: 'single' | 'married' | 'other';
  qualification?: string;
  university?: string;
  grade?: string;
  graduationYear?: string;
  cvUrl?: string;
  interviewDate?: string;
  interviewResult?: string;
  isPromoted?: boolean;
}

export interface AttendanceRecord {
  id: string;
  employeeId: string;
  employeeName: string;
  date: string; // YYYY-MM-DD
  checkIn: string; // HH:MM
  checkOut: string; // HH:MM
}

export interface LeaveRequest {
  id: string;
  employeeId: string;
  employeeName: string;
  leaveType: 'annual' | 'sick' | 'unpaid';
  startDate: string; // YYYY-MM-DD
  endDate: string; // YYYY-MM-DD
  reason: string;
  status: 'pending' | 'approved' | 'rejected';
}

export interface Penalty {
  id: string;
  employeeId: string;
  employeeName: string;
  date: string; // YYYY-MM-DD
  type: 'warning' | 'deduction';
  reason: string;
  amount?: number;
}

export interface Reward {
  id: string;
  employeeId: string;
  employeeName: string;
  date: string; // YYYY-MM-DD
  type: 'bonus' | 'praise';
  reason: string;
  amount?: number;
}

export interface Payslip {
  employeeId: string;
  employeeName: string;
  baseSalary: number;
  rewards: { reason: string; amount: number }[];
  penalties: { reason:string; amount: number }[];
  totalRewards: number;
  totalDeductions: number;
  netSalary: number;
}

export interface Payroll {
  id: string;
  month: number; // 1-12
  year: number;
  status: 'draft' | 'finalized';
  payslips: Payslip[];
  totalNetPayable: number;
  createdAt: string;
}

// --- Accounting Module Types ---

export type AccountType = 'asset' | 'liability' | 'equity' | 'revenue' | 'expense';

export interface Account {
  id: string;
  name: string;
  code: string;
  type: AccountType;
  parentId: string | null;
  balance: number;
}

export interface JournalEntryItem {
  accountId: string;
  accountName: string;
  debit: number;
  credit: number;
}

export interface JournalEntry {
  id: string;
  date: string; // YYYY-MM-DD
  description: string;
  type: 'opening' | 'general';
  items: JournalEntryItem[];
  isAutoGenerated: boolean;
  sourceId?: string; // e.g., expenseId, assetId
}

export interface Expense {
  id: string;
  date: string; // YYYY-MM-DD
  description: string;
  amount: number;
  expenseAccountId: string;
  paymentAccountId: string; // e.g., Cash, Bank
}

export type CustodyTransactionType = 'receipt' | 'settlement';

export interface Custody {
  id: string;
  employeeId: string;
  employeeName: string;
  date: string; // YYYY-MM-DD
  type: CustodyTransactionType;
  description: string;
  amount: number;
}

export interface FixedAsset {
  id: string;
  name: string;
  purchaseDate: string; // YYYY-MM-DD
  purchasePrice: number;
  depreciationRate: number; // Annual percentage
  usefulLife: number; // In years
  status: 'active' | 'disposed';
}

// --- Sales Module Types ---

export interface Customer {
  id: string;
  name: string;
  email?: string;
  phone?: string;
  address?: string;
}

export interface SalesInvoiceItem {
  description: string;
  quantity: number;
  unitPrice: number;
  total: number;
}

export interface SalesInvoice {
  id: string;
  customerId: string;
  customerName: string;
  date: string; // YYYY-MM-DD
  items: SalesInvoiceItem[];
  totalAmount: number;
  status: 'draft' | 'sent' | 'paid' | 'overdue';
}

export interface ReceiptVoucher {
  id: string;
  customerId: string;
  customerName: string;
  date: string; // YYYY-MM-DD
  amount: number;
  paymentAccountId: string; // Cash or Bank
  description: string;
}

// --- Projects Module Types ---

export interface Project {
  id: string;
  name: string;
  description: string;
  status: 'planning' | 'in-progress' | 'completed';
  startDate: string; // YYYY-MM-DD
  endDate: string; // YYYY-MM-DD
  budget: number;
}

export interface Task {
  id: string;
  projectId: string;
  projectName: string;
  name: string;
  description: string;
  status: 'todo' | 'in-progress' | 'done';
  assigneeId?: string;
  assigneeName?: string;
  dueDate: string; // YYYY-MM-DD
}