import React, { useState, useEffect } from 'react';
import { db, addDoc, collection } from '../services/firebase';
import { Employee, Account, Custody, JournalEntry, JournalEntryItem } from '../types';

interface CustodyModalProps {
    isOpen: boolean;
    onClose: () => void;
    onSaveSuccess: () => void;
    employees: Employee[];
    accounts: Account[];
    companyId: string;
    inputStyle: string;
    createAutoJournalEntry: (entryData: Omit<JournalEntry, 'id' | 'isAutoGenerated'>) => Promise<void>;
}
export const CustodyModal: React.FC<CustodyModalProps> = ({ isOpen, onClose, onSaveSuccess, employees, accounts, companyId, inputStyle, createAutoJournalEntry }) => {
    const [custody, setCustody] = useState<Partial<Custody>>({ date: new Date().toISOString().split('T')[0], type: 'receipt' });
    const [saving, setSaving] = useState(false);

     useEffect(() => {
        if (!isOpen) setCustody({ date: new Date().toISOString().split('T')[0], type: 'receipt' });
    }, [isOpen]);

    if (!isOpen) return null;

    const handleSave = async (e: React.FormEvent) => {
        e.preventDefault();
        if(!custody.employeeId) return;
        setSaving(true);
        const employeeName = employees.find(emp => emp.id === custody.employeeId)?.name || '';
        const data = {...custody, employeeName, date: custody.date || new Date().toISOString().split('T')[0], amount: custody.amount || 0};
        try {
            const docRef = await addDoc(collection(db, 'companies', companyId, 'custody'), data);
            const employeeCustodyAccount = accounts.find(a => a.name.includes("عهد الموظفين"));
            const cashAccount = accounts.find(a => a.name.includes("الصندوق") || a.name.includes("البنك"));
            
            if (employeeCustodyAccount && cashAccount) {
                let items: JournalEntryItem[] = [];
                if (data.type === 'receipt') {
                    items = [
                        { accountId: employeeCustodyAccount.id, accountName: employeeCustodyAccount.name, debit: data.amount, credit: 0 },
                        { accountId: cashAccount.id, accountName: cashAccount.name, debit: 0, credit: data.amount }
                    ];
                } else { // settlement
                     items = [
                        { accountId: cashAccount.id, accountName: cashAccount.name, debit: data.amount, credit: 0 },
                        { accountId: employeeCustodyAccount.id, accountName: employeeCustodyAccount.name, debit: 0, credit: data.amount }
                    ];
                }
                await createAutoJournalEntry({
                    date: data.date,
                    description: `عهدة موظف ${data.employeeName}: ${data.description}`,
                    type: 'general',
                    items,
                    sourceId: docRef.id
                });
            } else {
                alert("يرجى التأكد من وجود حساب 'عهد الموظفين' و 'الصندوق' في دليل الحسابات.")
            }
            onSaveSuccess();
            onClose();
        } catch (error) { console.error(error); } finally { setSaving(false); }
    };
    return (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex justify-center items-center z-50">
            <div className="bg-white rounded-lg p-6 w-full max-w-lg">
                <h3 className="font-bold text-lg mb-4">إضافة حركة عهدة</h3>
                <form onSubmit={handleSave} className="space-y-4">
                    <select value={custody.employeeId || ''} onChange={e => setCustody(p=>({...p, employeeId: e.target.value}))} className={inputStyle} required><option value="" disabled>اختر موظف</option>{employees.map(e => <option key={e.id} value={e.id}>{e.name}</option>)}</select>
                    <input type="date" value={custody.date || ''} onChange={e => setCustody(p=>({...p, date: e.target.value}))} className={inputStyle} />
                    <select value={custody.type} onChange={e => setCustody(p=>({...p, type: e.target.value as any}))} className={inputStyle}><option value="receipt">استلام عهدة</option><option value="settlement">تسوية عهدة</option></select>
                    <input type="text" placeholder="الوصف" value={custody.description || ''} onChange={e => setCustody(p=>({...p, description: e.target.value}))} className={inputStyle} required />
                    <input type="number" step="0.01" placeholder="المبلغ" value={custody.amount || ''} onChange={e => setCustody(p=>({...p, amount: parseFloat(e.target.value)}))} className={inputStyle} required />
                    <div className="mt-6 flex justify-end gap-3"><button type="button" onClick={onClose} className="bg-gray-200 py-2 px-4 rounded-lg">إلغاء</button><button type="submit" disabled={saving} className="bg-blue-600 text-white py-2 px-4 rounded-lg disabled:opacity-50">{saving ? '...' : 'حفظ'}</button></div>
                </form>
            </div>
        </div>
    );
};
