import React, { useState, useEffect } from 'react';
import { db, addDoc, collection } from '../services/firebase';
import { Account, AccountType, Expense, JournalEntry } from '../types';

interface ExpenseModalProps {
    isOpen: boolean;
    onClose: () => void;
    onSaveSuccess: () => void;
    accounts: Account[];
    accountsByType: Record<AccountType, Account[]>;
    companyId: string;
    inputStyle: string;
    createAutoJournalEntry: (entryData: Omit<JournalEntry, 'id' | 'isAutoGenerated'>) => Promise<void>;
}

export const ExpenseModal: React.FC<ExpenseModalProps> = ({ isOpen, onClose, onSaveSuccess, accounts, accountsByType, companyId, inputStyle, createAutoJournalEntry }) => {
    const [expense, setExpense] = useState<Partial<Expense>>({ date: new Date().toISOString().split('T')[0] });
    const [saving, setSaving] = useState(false);

    useEffect(() => {
        if (!isOpen) setExpense({ date: new Date().toISOString().split('T')[0] });
    }, [isOpen]);

    if (!isOpen) return null;

    const handleSave = async (e: React.FormEvent) => {
        e.preventDefault();
        if(!expense.expenseAccountId || !expense.paymentAccountId) return;
        setSaving(true);
        const expenseData = {
            ...expense,
            date: expense.date || new Date().toISOString().split('T')[0],
            amount: expense.amount || 0,
        };
        try {
            const docRef = await addDoc(collection(db, 'companies', companyId, 'expenses'), expenseData);
            const expenseAccountName = accounts.find(a => a.id === expenseData.expenseAccountId)?.name;
            const paymentAccountName = accounts.find(a => a.id === expenseData.paymentAccountId)?.name;
            await createAutoJournalEntry({
                date: expenseData.date,
                description: `مصروف: ${expenseData.description}`,
                type: 'general',
                items: [
                    { accountId: expenseData.expenseAccountId, accountName: expenseAccountName || 'حساب مصروف', debit: expenseData.amount, credit: 0 },
                    { accountId: expenseData.paymentAccountId, accountName: paymentAccountName || 'حساب سداد', debit: 0, credit: expenseData.amount }
                ],
                sourceId: docRef.id,
            });
            onSaveSuccess();
            onClose();
        } catch (error) { console.error(error); } finally { setSaving(false); }
    };

    return (
         <div className="fixed inset-0 bg-black bg-opacity-50 flex justify-center items-center z-50">
            <div className="bg-white rounded-lg p-6 w-full max-w-lg">
                <h3 className="font-bold text-lg mb-4">إضافة مصروف</h3>
                <form onSubmit={handleSave} className="space-y-4">
                    <input type="date" value={expense.date || ''} onChange={e => setExpense(p=>({...p, date: e.target.value}))} className={inputStyle} />
                    <input type="text" placeholder="الوصف" value={expense.description || ''} onChange={e => setExpense(p=>({...p, description: e.target.value}))} className={inputStyle} required />
                    <input type="number" step="0.01" placeholder="المبلغ" value={expense.amount || ''} onChange={e => setExpense(p=>({...p, amount: parseFloat(e.target.value)}))} className={inputStyle} required />
                    <select value={expense.expenseAccountId || ''} onChange={e => setExpense(p=>({...p, expenseAccountId: e.target.value}))} className={inputStyle} required><option value="" disabled>اختر حساب المصروف</option>{accountsByType.expense.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select>
                    <select value={expense.paymentAccountId || ''} onChange={e => setExpense(p=>({...p, paymentAccountId: e.target.value}))} className={inputStyle} required><option value="" disabled>اختر حساب السداد (الصندوق/البنك)</option>{accounts.filter(a=> a.code.startsWith('11')).map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select>
                    <div className="mt-6 flex justify-end gap-3"><button type="button" onClick={onClose} className="bg-gray-200 py-2 px-4 rounded-lg">إلغاء</button><button type="submit" disabled={saving} className="bg-blue-600 text-white py-2 px-4 rounded-lg disabled:opacity-50">{saving ? '...' : 'حفظ'}</button></div>
                </form>
            </div>
        </div>
    );
};
