import React, { useState, useEffect } from 'react';
import { db, addDoc, collection } from '../services/firebase';
import { Account, JournalEntry, JournalEntryItem } from '../types';

interface JournalEntryModalProps {
    isOpen: boolean;
    onClose: () => void;
    onSaveSuccess: () => void;
    accounts: Account[];
    companyId: string;
    inputStyle: string;
}

export const JournalEntryModal: React.FC<JournalEntryModalProps> = ({ isOpen, onClose, onSaveSuccess, accounts, companyId, inputStyle }) => {
    const [entry, setEntry] = useState<Partial<JournalEntry>>({ type: 'general', date: new Date().toISOString().split('T')[0], items: [{ accountId: '', accountName: '', debit: 0, credit: 0 }, { accountId: '', accountName: '', debit: 0, credit: 0 }]});
    const [saving, setSaving] = useState(false);
    const [balanceError, setBalanceError] = useState('');

    useEffect(() => {
        if (!isOpen) {
            setEntry({ type: 'general', date: new Date().toISOString().split('T')[0], items: [{ accountId: '', accountName: '', debit: 0, credit: 0 }, { accountId: '', accountName: '', debit: 0, credit: 0 }]});
            setBalanceError('');
        }
    }, [isOpen]);

    if (!isOpen) return null;

    const handleSave = async (e: React.FormEvent) => {
        e.preventDefault();
        if (!entry.items || entry.items.length < 2) {
            setBalanceError("يجب أن يحتوي القيد على طرفين على الأقل.");
            return;
        }
        const totalDebit = entry.items.reduce((sum, item) => sum + (item.debit || 0), 0);
        const totalCredit = entry.items.reduce((sum, item) => sum + (item.credit || 0), 0);

        if (totalDebit !== totalCredit) {
            setBalanceError("إجمالي المدين يجب أن يساوي إجمالي الدائن.");
            return;
        }
        if (totalDebit === 0) {
            setBalanceError("يجب ألا يكون إجمالي القيد صفراً.");
            return;
        }

        setBalanceError('');
        setSaving(true);
        const { id, ...data } = entry;
        const entryData = {
            ...data,
            date: data.date || new Date().toISOString().split('T')[0],
            isAutoGenerated: false,
        };

        try {
            await addDoc(collection(db, 'companies', companyId, 'journalEntries'), entryData);
            onSaveSuccess();
            onClose();
        } catch (error) { 
            console.error(error); 
        } finally { 
            setSaving(false); 
        }
    };

    const handleItemChange = (index: number, field: keyof JournalEntryItem, value: string) => {
        const newItems = [...(entry.items || [])];
        const item = { ...newItems[index] };
        if (field === 'accountId') {
            item.accountId = value;
            item.accountName = accounts.find(a => a.id === value)?.name || '';
        } else if (field === 'debit' || field === 'credit') {
            item[field] = parseFloat(value) || 0;
        }
        newItems[index] = item;
        setEntry(p => ({...p, items: newItems}));
    };

    const addItem = () => {
        const newItems = [...(entry.items || []), { accountId: '', accountName: '', debit: 0, credit: 0 }];
        setEntry(p => ({...p, items: newItems}));
    };

    const removeItem = (index: number) => {
        const newItems = (entry.items || []).filter((_, i) => i !== index);
        setEntry(p => ({...p, items: newItems}));
    };
    
    const totalDebit = entry.items?.reduce((sum, item) => sum + (item.debit || 0), 0) || 0;
    const totalCredit = entry.items?.reduce((sum, item) => sum + (item.credit || 0), 0) || 0;

    return (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex justify-center items-center z-50">
            <div className="bg-white rounded-lg p-6 w-full max-w-3xl max-h-[90vh] overflow-y-auto">
                <h3 className="font-bold text-lg mb-4">إضافة قيد يومية</h3>
                <form onSubmit={handleSave}>
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4">
                        <input type="date" value={entry.date || ''} onChange={e => setEntry(p=>({...p, date: e.target.value}))} className={inputStyle} />
                        <select value={entry.type} onChange={e=>setEntry(p=>({...p, type: e.target.value as any}))} className={inputStyle}><option value="general">قيد يومي</option><option value="opening">قيد افتتاحي</option></select>
                    </div>
                    <input type="text" placeholder="الوصف" value={entry.description || ''} onChange={e => setEntry(p=>({...p, description: e.target.value}))} className={`${inputStyle} w-full mb-4`} required/>
                    <div className="space-y-2">
                        {entry.items?.map((item, index) => (
                            <div key={index} className="flex items-center gap-2">
                                <select value={item.accountId} onChange={e => handleItemChange(index, 'accountId', e.target.value)} className={inputStyle} style={{width:'40%'}} required><option value="" disabled>اختر حساب</option>{accounts.sort((a,b) => a.code.localeCompare(b.code)).map(a=><option key={a.id} value={a.id}>{a.code} - {a.name}</option>)}</select>
                                <input type="number" step="0.01" placeholder="مدين" value={item.debit || ''} onChange={e => handleItemChange(index, 'debit', e.target.value)} className={inputStyle} style={{width:'20%'}} />
                                <input type="number" step="0.01" placeholder="دائن" value={item.credit || ''} onChange={e => handleItemChange(index, 'credit', e.target.value)} className={inputStyle} style={{width:'20%'}} />
                                <button type="button" onClick={() => removeItem(index)} className="bg-red-500 text-white p-2 rounded-lg text-xs">-</button>
                            </div>
                        ))}
                    </div>
                    <button type="button" onClick={addItem} className="mt-2 text-sm text-blue-600">+ إضافة طرف</button>
                    <div className="mt-4 border-t pt-2 flex justify-between font-bold">
                        <span>الإجمالي:</span>
                        <div>
                            <span className={`me-4 ${totalDebit !== totalCredit ? 'text-red-500' : ''}`}>مدين: {totalDebit.toFixed(2)}</span>
                            <span className={`${totalDebit !== totalCredit ? 'text-red-500' : ''}`}>دائن: {totalCredit.toFixed(2)}</span>
                        </div>
                    </div>
                    {balanceError && <p className="text-red-500 text-sm mt-2">{balanceError}</p>}
                    <div className="mt-6 flex justify-end gap-3">
                        <button type="button" onClick={onClose} className="bg-gray-200 py-2 px-4 rounded-lg">إلغاء</button>
                        <button type="submit" disabled={saving} className="bg-blue-600 text-white py-2 px-4 rounded-lg disabled:opacity-50">{saving ? '...' : 'حفظ'}</button>
                    </div>
                </form>
            </div>
        </div>
    );
};
