import React, { useState, useEffect } from 'react';
import { db, addDoc, collection } from '../services/firebase';
import { Customer, ReceiptVoucher, Account, JournalEntry } from '../types';

interface ReceiptVoucherModalProps {
    isOpen: boolean;
    onClose: () => void;
    onSaveSuccess: () => void;
    customers: Customer[];
    accounts: Account[];
    companyId: string;
    inputStyle: string;
    createAutoJournalEntry: (entryData: Omit<JournalEntry, 'id' | 'isAutoGenerated'>) => Promise<void>;
}

export const ReceiptVoucherModal: React.FC<ReceiptVoucherModalProps> = ({ isOpen, onClose, onSaveSuccess, customers, accounts, companyId, inputStyle, createAutoJournalEntry }) => {
    const [receipt, setReceipt] = useState<Partial<ReceiptVoucher>>({
        date: new Date().toISOString().split('T')[0]
    });
    const [saving, setSaving] = useState(false);

    useEffect(() => {
        if (!isOpen) {
            setReceipt({ date: new Date().toISOString().split('T')[0] });
        }
    }, [isOpen]);

    if (!isOpen) return null;

    const handleSave = async (e: React.FormEvent) => {
        e.preventDefault();
        if (!receipt.customerId || !receipt.amount || !receipt.paymentAccountId) return;
        setSaving(true);
        const customerName = customers.find(c => c.id === receipt.customerId)?.name || '';
        const receiptData = { ...receipt, customerName };

        try {
            const docRef = await addDoc(collection(db, 'companies', companyId, 'receiptVouchers'), receiptData);
            
            const paymentAccount = accounts.find(a => a.id === receipt.paymentAccountId);
            const customerAccount = accounts.find(a => a.name === 'العملاء'); // This is a simplification, might need better logic
            
            if (paymentAccount && customerAccount) {
                 await createAutoJournalEntry({
                    date: receiptData.date!,
                    description: `سند قبض من ${customerName}: ${receiptData.description}`,
                    type: 'general',
                    items: [
                        { accountId: paymentAccount.id, accountName: paymentAccount.name, debit: receiptData.amount!, credit: 0 },
                        { accountId: customerAccount.id, accountName: customerAccount.name, debit: 0, credit: receiptData.amount! }
                    ],
                    sourceId: docRef.id,
                });
            } else {
                alert("لم يتم العثور على حساب العملاء أو حساب السداد لإنشاء القيد التلقائي.");
            }
            
            onSaveSuccess();
            onClose();
        } catch (error) {
            console.error("Error saving receipt voucher:", error);
        } finally {
            setSaving(false);
        }
    };
    
    // Cash and bank accounts are usually current assets, starting with code '11'
    const paymentAccounts = accounts.filter(a => a.type === 'asset' && a.code.startsWith('11'));

    return (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex justify-center items-center z-50">
            <div className="bg-white rounded-lg p-6 w-full max-w-lg">
                <h3 className="font-bold text-lg mb-4">إضافة سند قبض</h3>
                <form onSubmit={handleSave} className="space-y-4">
                    <select value={receipt.customerId || ''} onChange={e => setReceipt(p => ({ ...p, customerId: e.target.value }))} className={inputStyle} required>
                        <option value="" disabled>اختر العميل</option>
                        {customers.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}
                    </select>
                    <input type="date" value={receipt.date || ''} onChange={e => setReceipt(p => ({ ...p, date: e.target.value }))} className={inputStyle} />
                    <input type="number" step="0.01" placeholder="المبلغ" value={receipt.amount || ''} onChange={e => setReceipt(p => ({ ...p, amount: parseFloat(e.target.value) }))} className={inputStyle} required />
                    <select value={receipt.paymentAccountId || ''} onChange={e => setReceipt(p => ({ ...p, paymentAccountId: e.target.value }))} className={inputStyle} required>
                        <option value="" disabled>اختر حساب الخزينة/البنك</option>
                        {paymentAccounts.map(a => <option key={a.id} value={a.id}>{a.name}</option>)}
                    </select>
                    <input type="text" placeholder="الوصف" value={receipt.description || ''} onChange={e => setReceipt(p => ({ ...p, description: e.target.value }))} className={inputStyle} required />
                     <div className="mt-6 flex justify-end gap-3">
                        <button type="button" onClick={onClose} className="bg-gray-200 py-2 px-4 rounded-lg">إلغاء</button>
                        <button type="submit" disabled={saving} className="bg-blue-600 text-white py-2 px-4 rounded-lg disabled:opacity-50">{saving ? '...' : 'حفظ'}</button>
                    </div>
                </form>
            </div>
        </div>
    );
};
